package Views;

import Controller.Controller;
import Controller.Database;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author albay
 */
public class MainMenu extends javax.swing.JDialog {

    Controller c = Controller.getController();
    Database d = Database.getDatabase();

    public MainMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        MMLabel.setText("¡Adelante, " + c.getUsername() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MMClose1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        MMHighscore = new javax.swing.JButton();
        MMSettings = new javax.swing.JButton();
        MMClose = new javax.swing.JButton();
        MMPlay = new javax.swing.JButton();
        MMLabel = new javax.swing.JLabel();
        MMDelete = new javax.swing.JButton();

        MMClose1.setText("Cerrar Sesión");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Main Menu");
        setResizable(false);

        MMHighscore.setText("Puntuaciones");
        MMHighscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMHighscoreActionPerformed(evt);
            }
        });

        MMSettings.setText("Opciones");
        MMSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMSettingsActionPerformed(evt);
            }
        });

        MMClose.setText("Cerrar Sesión");
        MMClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMCloseActionPerformed(evt);
            }
        });

        MMPlay.setText("Jugar");

        MMLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MMDelete.setText("Borrar Usuario");
        MMDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MMPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MMHighscore, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addComponent(MMSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MMLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(MMClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MMDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MMLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MMPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MMHighscore, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MMSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MMDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MMClose, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MMCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_MMCloseActionPerformed

    private void MMDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMDeleteActionPerformed
        DeleteUser du = new DeleteUser(null, true);
        du.setVisible(true);
        try {
            if (!d.userExists(c.getUsername())) {
                this.dispose();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "False Connection", JOptionPane.ERROR_MESSAGE);

        };
    }//GEN-LAST:event_MMDeleteActionPerformed

    private void MMSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMSettingsActionPerformed
        Settings s = new Settings(null, false);
        s.setVisible(true);
    }//GEN-LAST:event_MMSettingsActionPerformed

    private void MMHighscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMHighscoreActionPerformed
        Highscore h = new Highscore(null, false);
        h.setVisible(true);
    }//GEN-LAST:event_MMHighscoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainMenu dialog = new MainMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MMClose;
    private javax.swing.JButton MMClose1;
    private javax.swing.JButton MMDelete;
    private javax.swing.JButton MMHighscore;
    private javax.swing.JLabel MMLabel;
    private javax.swing.JButton MMPlay;
    private javax.swing.JButton MMSettings;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
