/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

/**
 *
 * @author albay
 */
public class New_User extends javax.swing.JDialog {

    /**
     * Creates new form New_User
     */
    public New_User(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nombre_newUser = new javax.swing.JTextField();
        Correo_newUser = new javax.swing.JTextField();
        Contraseña_newUser = new javax.swing.JPasswordField();
        Acceptar_newUser = new javax.swing.JButton();
        Cancelar_newUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Nombre_newUser.setText("Nombre");
        Nombre_newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_newUserActionPerformed(evt);
            }
        });

        Correo_newUser.setText("Correo");
        Correo_newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Correo_newUserActionPerformed(evt);
            }
        });

        Contraseña_newUser.setText("Contraseña");
        Contraseña_newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contraseña_newUserActionPerformed(evt);
            }
        });

        Acceptar_newUser.setText("Acceptar");
        Acceptar_newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acceptar_newUserActionPerformed(evt);
            }
        });

        Cancelar_newUser.setText("Cancelar");
        Cancelar_newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_newUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Acceptar_newUser)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cancelar_newUser))
                        .addComponent(Contraseña_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Correo_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(Nombre_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Correo_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Contraseña_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Acceptar_newUser)
                    .addComponent(Cancelar_newUser))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Nombre_newUser.getAccessibleContext().setAccessibleName("Nombre_newUser");
        Correo_newUser.getAccessibleContext().setAccessibleName("Correo_newUser");
        Contraseña_newUser.getAccessibleContext().setAccessibleName("Contraseña_newUser");
        Acceptar_newUser.getAccessibleContext().setAccessibleName("Acceptar_newUser");
        Cancelar_newUser.getAccessibleContext().setAccessibleName("Cancelar_newUser");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nombre_newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_newUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_newUserActionPerformed

    private void Correo_newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Correo_newUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Correo_newUserActionPerformed

    private void Contraseña_newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contraseña_newUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contraseña_newUserActionPerformed

    private void Acceptar_newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acceptar_newUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Acceptar_newUserActionPerformed

    private void Cancelar_newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_newUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancelar_newUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                New_User dialog = new New_User(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acceptar_newUser;
    private javax.swing.JButton Cancelar_newUser;
    private javax.swing.JPasswordField Contraseña_newUser;
    private javax.swing.JTextField Correo_newUser;
    private javax.swing.JTextField Nombre_newUser;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
