package Views;

import Controller.Controller;
import Controller.Database;
import Controller.Logica3EnRaya;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author albay
 */
public class TresEnRaya extends javax.swing.JDialog {

    Database d = Database.getDatabase();
    Controller c = Controller.getController();

    private JButton[][] botones;

    public TresEnRaya(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarJuego();
    }

    private void inicializarJuego() {
        Logica3EnRaya.inicializarTablero();
        actualizarTurno();
        botones = new JButton[][]{
            {Casila_00, Casila_01, Casila_02},
            {Casila_10, Casila_11, Casila_12},
            {Casila_20, Casila_21, Casila_22}
        };

        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                final int fila = i;
                final int columna = j;
                botones[i][j].addActionListener(e -> realizarMovimiento(fila, columna));
            }
        }
    }

    private void realizarMovimiento(int fila, int columna) {
        if (Logica3EnRaya.movimientoValido(fila, columna)) {
            Logica3EnRaya.hacerMovimiento(fila, columna);
            botones[fila][columna].setText(String.valueOf(Logica3EnRaya.getJugadorActual()));
            verificarJuego();
        }
    }

    private void verificarJuego() {
        if (Logica3EnRaya.hayGanador()) {
            JOptionPane.showMessageDialog(this, "¡El jugador " + Logica3EnRaya.getJugadorActual() + " ha ganado!");
            try {
                if (Logica3EnRaya.getJugadorActual() == 'X') {
                    d.addWin(c.getUsername());
                }
                d.addGame(c.getUsername());
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "False Connection", JOptionPane.ERROR_MESSAGE);
            }
            reiniciarJuego();
        } else if (Logica3EnRaya.esEmpate()) {
            JOptionPane.showMessageDialog(this, "¡Empate!");
            try {
                d.addGame(c.getUsername());
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "False Connection", JOptionPane.ERROR_MESSAGE);
            }
            reiniciarJuego();
        } else {
            Logica3EnRaya.cambiarTurno();
            actualizarTurno();
            if (Logica3EnRaya.getJugadorActual() == 'O') {
                Logica3EnRaya.hacerMovimientoCPU(botones);
                verificarJuego();
            }
        }
    }

    private void actualizarTurno() {
        jugadorTF.setText("Turno de: " + Logica3EnRaya.getJugadorActual());
    }

    private void reiniciarJuego() {
        Logica3EnRaya.inicializarTablero();
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                botones[i][j].setText("");
            }
        }
        actualizarTurno();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            TresEnRaya dialog = new TresEnRaya(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Casila_00 = new javax.swing.JButton();
        Casila_10 = new javax.swing.JButton();
        Casila_20 = new javax.swing.JButton();
        Casila_01 = new javax.swing.JButton();
        Casila_11 = new javax.swing.JButton();
        Casila_21 = new javax.swing.JButton();
        Casila_02 = new javax.swing.JButton();
        Casila_12 = new javax.swing.JButton();
        Casila_22 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jugadorTF = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Game");

        jugadorTF.setColumns(20);
        jugadorTF.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jugadorTF.setRows(1);
        jugadorTF.setEnabled(false);
        jugadorTF.setFocusable(false);
        jScrollPane1.setViewportView(jugadorTF);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Casila_20, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(Casila_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Casila_00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Casila_11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casila_21, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casila_01, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Casila_12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casila_02, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casila_22, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Casila_00, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(Casila_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Casila_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Casila_10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casila_11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casila_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Casila_21, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casila_20, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casila_22, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Casila_00.getAccessibleContext().setAccessibleName("Casilla_00");
        Casila_10.getAccessibleContext().setAccessibleName("Casila_10");
        Casila_20.getAccessibleContext().setAccessibleName("Casila_20");
        Casila_01.getAccessibleContext().setAccessibleName("Casila_01");
        Casila_11.getAccessibleContext().setAccessibleName("Casila_11");
        Casila_02.getAccessibleContext().setAccessibleName("Casilla_02");
        Casila_12.getAccessibleContext().setAccessibleName("Casila_12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Casila_00;
    private javax.swing.JButton Casila_01;
    private javax.swing.JButton Casila_02;
    private javax.swing.JButton Casila_10;
    private javax.swing.JButton Casila_11;
    private javax.swing.JButton Casila_12;
    private javax.swing.JButton Casila_20;
    private javax.swing.JButton Casila_21;
    private javax.swing.JButton Casila_22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jugadorTF;
    // End of variables declaration//GEN-END:variables
}
